---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: {{WORKER_IMAGE}}
        command: ["celery", "-A", "reana_workflow_controller.celeryapp", "worker", "-l", "info"]
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        env:
        {% set environment=RW_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
