---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yadage-default-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yadage-default-worker
    spec:
      containers:
      - name: yadage-default-worker
        image: {{WORKFLOW_ENGINE_YADAGE_IMAGE}}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        {%- if DEPLOYMENT != 'prod' %}
        tty: true
        stdin: true
        {% endif %}
        env:
        - name: QUEUE_ENV
          value: yadage-default-queue
        - name: REANA_WORKFLOW_ENGINE_YADAGE_EXPERIMENT
          value: default
        - name: SHARED_VOLUME_PATH
          value: /reana
        {% set environment=RWEYADAGE_ENVIRONMENT %}
        {% for envvar in environment %}
        {% for key, value in envvar.items() %}
        - name: {{key}}
          value: "{{value}}"
        {% endfor %}
        {% endfor %}
        volumeMounts:
        - name: default-shared-volume
          mountPath: /reana
        {%- if DEPLOYMENT == 'prod' %}
        - name: cms-cvmfs-volume
          mountPath: /cvmfs/cms.cern.ch
        - name: atlas-cvmfs-volume
          mountPath: /cvmfs/atlas.cern.ch
        - name: alice-cvmfs-volume
          mountPath: /cvmfs/alice.cern.ch
        - name: lhcb-cvmfs-volume
          mountPath: /cvmfs/lhcb.cern.ch
        {% endif %}
        {% set mountpoints=RWEYADAGE_MOUNTPOINTS %}
        {% for mount in mountpoints %}
        - mountPath: {{mount['path'].split(':')[1]}}
          name: {{mount['name']}}
        {% endfor %}
      volumes:
      - name: default-shared-volume
        {%- if DEPLOYMENT == 'prod' %}
        persistentVolumeClaim:
          claimName: manila-cephfs-pvc
          readOnly: false
      - name: cms-cvmfs-volume
        persistentVolumeClaim:
          claimName: csi-cvmfs-cms-pvc
          readOnly: true
      - name: atlas-cvmfs-volume
        persistentVolumeClaim:
          claimName: csi-cvmfs-atlas-pvc
          readOnly: true
      - name: lhcb-cvmfs-volume
        persistentVolumeClaim:
          claimName: csi-cvmfs-lhcb-pvc
          readOnly: true
      - name: alice-cvmfs-volume
        persistentVolumeClaim:
          claimName: csi-cvmfs-alice-pvc
          readOnly: true
        {% else %}
        hostPath:
            path: "{{ROOT_PATH}}"
        {% endif %}
      {% for mount in mountpoints %}
      - name: {{mount['name']}}
        {{mount['type']}}:
          path: {{mount['path'].split(':')[0]}}
      {% endfor %}
